// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: comet/comet.proto

package comet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CometClient is the client API for Comet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CometClient interface {
	// push by user keys
	PushUserKeys(ctx context.Context, in *PushUserKeysReq, opts ...grpc.CallOption) (*PushUserKeysReply, error)
	// push by room's user
	PushUserRoom(ctx context.Context, in *PushUserRoomReq, opts ...grpc.CallOption) (*PushUserRoomReply, error)
	// push by every user
	PushUserAll(ctx context.Context, in *PushUserAllReq, opts ...grpc.CallOption) (*PushUserAllReply, error)
	// get all rooms
	GetAllRoomId(ctx context.Context, in *GetAllRoomIdReq, opts ...grpc.CallOption) (*GetAllRoomIdReply, error)
}

type cometClient struct {
	cc grpc.ClientConnInterface
}

func NewCometClient(cc grpc.ClientConnInterface) CometClient {
	return &cometClient{cc}
}

func (c *cometClient) PushUserKeys(ctx context.Context, in *PushUserKeysReq, opts ...grpc.CallOption) (*PushUserKeysReply, error) {
	out := new(PushUserKeysReply)
	err := c.cc.Invoke(ctx, "/imfun.comet.Comet/PushUserKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) PushUserRoom(ctx context.Context, in *PushUserRoomReq, opts ...grpc.CallOption) (*PushUserRoomReply, error) {
	out := new(PushUserRoomReply)
	err := c.cc.Invoke(ctx, "/imfun.comet.Comet/PushUserRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) PushUserAll(ctx context.Context, in *PushUserAllReq, opts ...grpc.CallOption) (*PushUserAllReply, error) {
	out := new(PushUserAllReply)
	err := c.cc.Invoke(ctx, "/imfun.comet.Comet/PushUserAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) GetAllRoomId(ctx context.Context, in *GetAllRoomIdReq, opts ...grpc.CallOption) (*GetAllRoomIdReply, error) {
	out := new(GetAllRoomIdReply)
	err := c.cc.Invoke(ctx, "/imfun.comet.Comet/GetAllRoomId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CometServer is the server API for Comet service.
// All implementations must embed UnimplementedCometServer
// for forward compatibility
type CometServer interface {
	// push by user keys
	PushUserKeys(context.Context, *PushUserKeysReq) (*PushUserKeysReply, error)
	// push by room's user
	PushUserRoom(context.Context, *PushUserRoomReq) (*PushUserRoomReply, error)
	// push by every user
	PushUserAll(context.Context, *PushUserAllReq) (*PushUserAllReply, error)
	// get all rooms
	GetAllRoomId(context.Context, *GetAllRoomIdReq) (*GetAllRoomIdReply, error)
	mustEmbedUnimplementedCometServer()
}

// UnimplementedCometServer must be embedded to have forward compatible implementations.
type UnimplementedCometServer struct {
}

func (UnimplementedCometServer) PushUserKeys(context.Context, *PushUserKeysReq) (*PushUserKeysReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushUserKeys not implemented")
}
func (UnimplementedCometServer) PushUserRoom(context.Context, *PushUserRoomReq) (*PushUserRoomReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushUserRoom not implemented")
}
func (UnimplementedCometServer) PushUserAll(context.Context, *PushUserAllReq) (*PushUserAllReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushUserAll not implemented")
}
func (UnimplementedCometServer) GetAllRoomId(context.Context, *GetAllRoomIdReq) (*GetAllRoomIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRoomId not implemented")
}
func (UnimplementedCometServer) mustEmbedUnimplementedCometServer() {}

// UnsafeCometServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CometServer will
// result in compilation errors.
type UnsafeCometServer interface {
	mustEmbedUnimplementedCometServer()
}

func RegisterCometServer(s grpc.ServiceRegistrar, srv CometServer) {
	s.RegisterService(&Comet_ServiceDesc, srv)
}

func _Comet_PushUserKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushUserKeysReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).PushUserKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imfun.comet.Comet/PushUserKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).PushUserKeys(ctx, req.(*PushUserKeysReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_PushUserRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushUserRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).PushUserRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imfun.comet.Comet/PushUserRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).PushUserRoom(ctx, req.(*PushUserRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_PushUserAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushUserAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).PushUserAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imfun.comet.Comet/PushUserAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).PushUserAll(ctx, req.(*PushUserAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_GetAllRoomId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRoomIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).GetAllRoomId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imfun.comet.Comet/GetAllRoomId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).GetAllRoomId(ctx, req.(*GetAllRoomIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Comet_ServiceDesc is the grpc.ServiceDesc for Comet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imfun.comet.Comet",
	HandlerType: (*CometServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushUserKeys",
			Handler:    _Comet_PushUserKeys_Handler,
		},
		{
			MethodName: "PushUserRoom",
			Handler:    _Comet_PushUserRoom_Handler,
		},
		{
			MethodName: "PushUserAll",
			Handler:    _Comet_PushUserAll_Handler,
		},
		{
			MethodName: "GetAllRoomId",
			Handler:    _Comet_GetAllRoomId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comet/comet.proto",
}
