// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.7.1
// source: comet/comet.proto

package comet

import (
	protocol "github.com/zhixunjie/im-fun/api/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// users
type PushUserKeysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKeys []string        `protobuf:"bytes,1,rep,name=userKeys,proto3" json:"userKeys,omitempty"`
	Proto    *protocol.Proto `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	SubId    int32           `protobuf:"varint,3,opt,name=subId,proto3" json:"subId,omitempty"`
}

func (x *PushUserKeysReq) Reset() {
	*x = PushUserKeysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_comet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushUserKeysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUserKeysReq) ProtoMessage() {}

func (x *PushUserKeysReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_comet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUserKeysReq.ProtoReflect.Descriptor instead.
func (*PushUserKeysReq) Descriptor() ([]byte, []int) {
	return file_comet_comet_proto_rawDescGZIP(), []int{0}
}

func (x *PushUserKeysReq) GetUserKeys() []string {
	if x != nil {
		return x.UserKeys
	}
	return nil
}

func (x *PushUserKeysReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *PushUserKeysReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

type PushUserKeysReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushUserKeysReply) Reset() {
	*x = PushUserKeysReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_comet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushUserKeysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUserKeysReply) ProtoMessage() {}

func (x *PushUserKeysReply) ProtoReflect() protoreflect.Message {
	mi := &file_comet_comet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUserKeysReply.ProtoReflect.Descriptor instead.
func (*PushUserKeysReply) Descriptor() ([]byte, []int) {
	return file_comet_comet_proto_rawDescGZIP(), []int{1}
}

// all users
type PushUserAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proto *protocol.Proto `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	SubId int32           `protobuf:"varint,2,opt,name=subId,proto3" json:"subId,omitempty"`
	Speed int32           `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *PushUserAllReq) Reset() {
	*x = PushUserAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_comet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushUserAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUserAllReq) ProtoMessage() {}

func (x *PushUserAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_comet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUserAllReq.ProtoReflect.Descriptor instead.
func (*PushUserAllReq) Descriptor() ([]byte, []int) {
	return file_comet_comet_proto_rawDescGZIP(), []int{2}
}

func (x *PushUserAllReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *PushUserAllReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *PushUserAllReq) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type PushUserAllReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushUserAllReply) Reset() {
	*x = PushUserAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_comet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushUserAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUserAllReply) ProtoMessage() {}

func (x *PushUserAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_comet_comet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUserAllReply.ProtoReflect.Descriptor instead.
func (*PushUserAllReply) Descriptor() ([]byte, []int) {
	return file_comet_comet_proto_rawDescGZIP(), []int{3}
}

// room users
type PushUserRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string          `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Proto  *protocol.Proto `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	SubId  int32           `protobuf:"varint,3,opt,name=subId,proto3" json:"subId,omitempty"`
}

func (x *PushUserRoomReq) Reset() {
	*x = PushUserRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_comet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushUserRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUserRoomReq) ProtoMessage() {}

func (x *PushUserRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_comet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUserRoomReq.ProtoReflect.Descriptor instead.
func (*PushUserRoomReq) Descriptor() ([]byte, []int) {
	return file_comet_comet_proto_rawDescGZIP(), []int{4}
}

func (x *PushUserRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PushUserRoomReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *PushUserRoomReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

type PushUserRoomReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushUserRoomReply) Reset() {
	*x = PushUserRoomReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_comet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushUserRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUserRoomReply) ProtoMessage() {}

func (x *PushUserRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_comet_comet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUserRoomReply.ProtoReflect.Descriptor instead.
func (*PushUserRoomReply) Descriptor() ([]byte, []int) {
	return file_comet_comet_proto_rawDescGZIP(), []int{5}
}

// room's
type GetAllRoomIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllRoomIdReq) Reset() {
	*x = GetAllRoomIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_comet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRoomIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomIdReq) ProtoMessage() {}

func (x *GetAllRoomIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_comet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomIdReq.ProtoReflect.Descriptor instead.
func (*GetAllRoomIdReq) Descriptor() ([]byte, []int) {
	return file_comet_comet_proto_rawDescGZIP(), []int{6}
}

type GetAllRoomIdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms map[string]bool `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetAllRoomIdReply) Reset() {
	*x = GetAllRoomIdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_comet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRoomIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomIdReply) ProtoMessage() {}

func (x *GetAllRoomIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_comet_comet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomIdReply.ProtoReflect.Descriptor instead.
func (*GetAllRoomIdReply) Descriptor() ([]byte, []int) {
	return file_comet_comet_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllRoomIdReply) GetRooms() map[string]bool {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_comet_comet_proto protoreflect.FileDescriptor

var file_comet_comet_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74,
	0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x0f, 0x50, 0x75, 0x73,
	0x68, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x50,
	0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x69, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x73, 0x75, 0x62, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x50,
	0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x6c, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6d, 0x66, 0x75,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x22, 0x13, 0x0a,
	0x11, 0x50, 0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x22, 0x8e, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x05, 0x72,
	0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x69, 0x6d, 0x66,
	0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xbc, 0x02, 0x0a, 0x05, 0x43, 0x6f, 0x6d, 0x65, 0x74,
	0x12, 0x4c, 0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73,
	0x12, 0x1c, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x50,
	0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1e,
	0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x50, 0x75, 0x73,
	0x68, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c,
	0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1c,
	0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x50, 0x75, 0x73,
	0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x69,
	0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x0b,
	0x50, 0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x12, 0x1b, 0x2e, 0x69, 0x6d,
	0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e,
	0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e,
	0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f,
	0x6d, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x69, 0x78, 0x75, 0x6e, 0x6a, 0x69, 0x65, 0x2f, 0x69, 0x6d,
	0x2d, 0x66, 0x75, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x3b, 0x63,
	0x6f, 0x6d, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comet_comet_proto_rawDescOnce sync.Once
	file_comet_comet_proto_rawDescData = file_comet_comet_proto_rawDesc
)

func file_comet_comet_proto_rawDescGZIP() []byte {
	file_comet_comet_proto_rawDescOnce.Do(func() {
		file_comet_comet_proto_rawDescData = protoimpl.X.CompressGZIP(file_comet_comet_proto_rawDescData)
	})
	return file_comet_comet_proto_rawDescData
}

var file_comet_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_comet_comet_proto_goTypes = []interface{}{
	(*PushUserKeysReq)(nil),   // 0: imfun.comet.PushUserKeysReq
	(*PushUserKeysReply)(nil), // 1: imfun.comet.PushUserKeysReply
	(*PushUserAllReq)(nil),    // 2: imfun.comet.PushUserAllReq
	(*PushUserAllReply)(nil),  // 3: imfun.comet.PushUserAllReply
	(*PushUserRoomReq)(nil),   // 4: imfun.comet.PushUserRoomReq
	(*PushUserRoomReply)(nil), // 5: imfun.comet.PushUserRoomReply
	(*GetAllRoomIdReq)(nil),   // 6: imfun.comet.GetAllRoomIdReq
	(*GetAllRoomIdReply)(nil), // 7: imfun.comet.GetAllRoomIdReply
	nil,                       // 8: imfun.comet.GetAllRoomIdReply.RoomsEntry
	(*protocol.Proto)(nil),    // 9: imfun.protocol.Proto
}
var file_comet_comet_proto_depIdxs = []int32{
	9, // 0: imfun.comet.PushUserKeysReq.proto:type_name -> imfun.protocol.Proto
	9, // 1: imfun.comet.PushUserAllReq.proto:type_name -> imfun.protocol.Proto
	9, // 2: imfun.comet.PushUserRoomReq.proto:type_name -> imfun.protocol.Proto
	8, // 3: imfun.comet.GetAllRoomIdReply.rooms:type_name -> imfun.comet.GetAllRoomIdReply.RoomsEntry
	0, // 4: imfun.comet.Comet.PushUserKeys:input_type -> imfun.comet.PushUserKeysReq
	4, // 5: imfun.comet.Comet.PushUserRoom:input_type -> imfun.comet.PushUserRoomReq
	2, // 6: imfun.comet.Comet.PushUserAll:input_type -> imfun.comet.PushUserAllReq
	6, // 7: imfun.comet.Comet.GetAllRoomId:input_type -> imfun.comet.GetAllRoomIdReq
	1, // 8: imfun.comet.Comet.PushUserKeys:output_type -> imfun.comet.PushUserKeysReply
	5, // 9: imfun.comet.Comet.PushUserRoom:output_type -> imfun.comet.PushUserRoomReply
	3, // 10: imfun.comet.Comet.PushUserAll:output_type -> imfun.comet.PushUserAllReply
	7, // 11: imfun.comet.Comet.GetAllRoomId:output_type -> imfun.comet.GetAllRoomIdReply
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_comet_comet_proto_init() }
func file_comet_comet_proto_init() {
	if File_comet_comet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comet_comet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushUserKeysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_comet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushUserKeysReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_comet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushUserAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_comet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushUserAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_comet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushUserRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_comet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushUserRoomReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_comet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRoomIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_comet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRoomIdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comet_comet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comet_comet_proto_goTypes,
		DependencyIndexes: file_comet_comet_proto_depIdxs,
		MessageInfos:      file_comet_comet_proto_msgTypes,
	}.Build()
	File_comet_comet_proto = out.File
	file_comet_comet_proto_rawDesc = nil
	file_comet_comet_proto_goTypes = nil
	file_comet_comet_proto_depIdxs = nil
}
