// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	grpc2 "github.com/zhixunjie/im-fun/internal/logic/api/grpc"
	"github.com/zhixunjie/im-fun/internal/logic/api/http"
	"github.com/zhixunjie/im-fun/internal/logic/biz"
	"github.com/zhixunjie/im-fun/internal/logic/conf"
	"github.com/zhixunjie/im-fun/internal/logic/data"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitGrpc(c *conf.Config) *grpc.Server {
	bizBiz := biz.NewBiz(c)
	dataData := data.NewData(c)
	contactRepo := data.NewContactRepo(dataData)
	contactUseCase := biz.NewContactUseCase(contactRepo)
	messageRepo := data.NewMessageRepo(dataData)
	messageUseCase := biz.NewMessageUseCase(messageRepo, contactUseCase)
	server := grpc2.NewServer(c, bizBiz, contactUseCase, messageUseCase)
	return server
}

func InitHttp(c *conf.Config) *http.Server {
	bizBiz := biz.NewBiz(c)
	dataData := data.NewData(c)
	contactRepo := data.NewContactRepo(dataData)
	contactUseCase := biz.NewContactUseCase(contactRepo)
	messageRepo := data.NewMessageRepo(dataData)
	messageUseCase := biz.NewMessageUseCase(messageRepo, contactUseCase)
	server := http.NewServer(c, bizBiz, contactUseCase, messageUseCase)
	return server
}
