// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	Contact   *contact
	Group     *group
	GroupUser *groupUser
	Message   *message
	Robot     *robot
	User      *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Contact = &Q.Contact
	Group = &Q.Group
	GroupUser = &Q.GroupUser
	Message = &Q.Message
	Robot = &Q.Robot
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		Contact:   newContact(db, opts...),
		Group:     newGroup(db, opts...),
		GroupUser: newGroupUser(db, opts...),
		Message:   newMessage(db, opts...),
		Robot:     newRobot(db, opts...),
		User:      newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Contact   contact
	Group     group
	GroupUser groupUser
	Message   message
	Robot     robot
	User      user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Contact:   q.Contact.clone(db),
		Group:     q.Group.clone(db),
		GroupUser: q.GroupUser.clone(db),
		Message:   q.Message.clone(db),
		Robot:     q.Robot.clone(db),
		User:      q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Contact:   q.Contact.replaceDB(db),
		Group:     q.Group.replaceDB(db),
		GroupUser: q.GroupUser.replaceDB(db),
		Message:   q.Message.replaceDB(db),
		Robot:     q.Robot.replaceDB(db),
		User:      q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Contact   IContactDo
	Group     IGroupDo
	GroupUser IGroupUserDo
	Message   IMessageDo
	Robot     IRobotDo
	User      IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Contact:   q.Contact.WithContext(ctx),
		Group:     q.Group.WithContext(ctx),
		GroupUser: q.GroupUser.WithContext(ctx),
		Message:   q.Message.WithContext(ctx),
		Robot:     q.Robot.WithContext(ctx),
		User:      q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
