// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatContact = "chat_contact"

// ChatContact 会话表（通信双方各有一行记录）
type ChatContact struct {
	ID           uint64    `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增id,主键" json:"id"`                    // 自增id,主键
	OwnerID      uint64    `gorm:"column:owner_id;not null;comment:会话拥有者" json:"owner_id"`                               // 会话拥有者
	OwnerType    uint32    `gorm:"column:owner_type;not null;comment:用户类型（owner_id）" json:"owner_type"`                  // 用户类型（owner_id）
	PeerID       uint64    `gorm:"column:peer_id;not null;comment:联系人（对方用户）" json:"peer_id"`                             // 联系人（对方用户）
	PeerType     uint32    `gorm:"column:peer_type;not null;comment:用户类型（peer_id）" json:"peer_type"`                     // 用户类型（peer_id）
	PeerAck      uint32    `gorm:"column:peer_ack;not null;comment:peer_id是否给owner发过消息，0：未发过，1：发过" json:"peer_ack"`      // peer_id是否给owner发过消息，0：未发过，1：发过
	LastMsgID    uint64    `gorm:"column:last_msg_id;not null;comment:聊天记录中，最新一条发送的私信id" json:"last_msg_id"`             // 聊天记录中，最新一条发送的私信id
	LastDelMsgID uint64    `gorm:"column:last_del_msg_id;not null;comment:聊天记录中，最后一次删除联系人时的私信id" json:"last_del_msg_id"` // 聊天记录中，最后一次删除联系人时的私信id
	VersionID    uint64    `gorm:"column:version_id;not null;comment:版本id（用于拉取会话框）" json:"version_id"`                   // 版本id（用于拉取会话框）
	SortKey      uint64    `gorm:"column:sort_key;not null;comment:会话展示顺序（按顺序展示会话）可修改顺序，如：置顶操作" json:"sort_key"`         // 会话展示顺序（按顺序展示会话）可修改顺序，如：置顶操作
	Status       uint32    `gorm:"column:status;not null;comment:联系人状态，0：正常，1：被删除" json:"status"`                        // 联系人状态，0：正常，1：被删除
	Labels       string    `gorm:"column:labels;not null;comment:会话标签，json字符串" json:"labels"`                            // 会话标签，json字符串
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`  // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`  // 更新时间
}

// TableName ChatContact's table name
func (*ChatContact) TableName() string {
	return TableNameChatContact
}
