// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChatIDCounter = "chat_id_counter"

// ChatIDCounter 计数器（用于生成各种ID）
type ChatIDCounter struct {
	Str       string `gorm:"column:str;primaryKey;comment:key字符串" json:"str"`             // key字符串
	StrCrc32  uint64 `gorm:"column:str_crc32;primaryKey;comment:key字符串" json:"str_crc32"` // key字符串
	Value     uint64 `gorm:"column:value;not null;comment:递增数值" json:"value"`             // 递增数值
	Timestamp uint64 `gorm:"column:timestamp;not null;comment:时间戳" json:"timestamp"`      // 时间戳
	CreatedAt uint64 `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt uint64 `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`   // 更新时间
}

// TableName ChatIDCounter's table name
func (*ChatIDCounter) TableName() string {
	return TableNameChatIDCounter
}
