// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatGroupMessageRef = "chat_group_message_ref"

// ChatGroupMessageRef 某条群组消息@的用户
type ChatGroupMessageRef struct {
	ID          uint64    `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                      // 自增id
	GroupID     uint64    `gorm:"column:group_id;not null;comment:群组id" json:"group_id"`                               // 群组id
	MsgID       uint64    `gorm:"column:msg_id;not null;comment:消息id" json:"msg_id"`                                   // 消息id
	MemberID    uint64    `gorm:"column:member_id;not null;comment:谁发起的@" json:"member_id"`                            // 谁发起的@
	RefMemberID uint64    `gorm:"column:ref_member_id;not null;comment:被@的群成员" json:"ref_member_id"`                   // 被@的群成员
	HasRead     uint32    `gorm:"column:has_read;not null;comment:是否已读，0：未读，1：已读" json:"has_read"`                     // 是否已读，0：未读，1：已读
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName ChatGroupMessageRef's table name
func (*ChatGroupMessageRef) TableName() string {
	return TableNameChatGroupMessageRef
}
