// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatGroupMessage = "chat_group_message"

// ChatGroupMessage 群组消息表（一条私信只有一行记录），减少messge表的空间
type ChatGroupMessage struct {
	ID         uint64    `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                      // 自增id
	MsgID      uint64    `gorm:"column:msg_id;not null;comment:消息唯一id（服务端生成）" json:"msg_id"`                          // 消息唯一id（服务端生成）
	SeqID      uint64    `gorm:"column:seq_id;not null;comment:消息唯一id（客户端生成）" json:"seq_id"`                          // 消息唯一id（客户端生成）
	MsgType    uint32    `gorm:"column:msg_type;not null;comment:消息类型" json:"msg_type"`                               // 消息类型
	Content    string    `gorm:"column:content;not null;comment:消息内容，json格式" json:"content"`                          // 消息内容，json格式
	SessionID  string    `gorm:"column:session_id;not null;comment:会话id" json:"session_id"`                           // 会话id
	SenderID   uint64    `gorm:"column:sender_id;not null;comment:消息发送者id" json:"sender_id"`                          // 消息发送者id
	SenderType uint32    `gorm:"column:sender_type;not null;comment:消息发送者的用户类型" json:"sender_type"`                   // 消息发送者的用户类型
	VersionID  uint64    `gorm:"column:version_id;not null;comment:版本id（用于拉取消息）" json:"version_id"`                   // 版本id（用于拉取消息）
	SortKey    uint64    `gorm:"column:sort_key;not null;comment:消息展示顺序（按顺序展示消息）" json:"sort_key"`                    // 消息展示顺序（按顺序展示消息）
	Status     uint32    `gorm:"column:status;not null;comment:消息状态" json:"status"`                                   // 消息状态
	HasRead    uint32    `gorm:"column:has_read;not null;comment:接收方是否已读，0：未读，1：已读" json:"has_read"`                  // 接收方是否已读，0：未读，1：已读
	RefUids    string    `gorm:"column:ref_uids;not null;comment:@我的用户（[1001,1002]）" json:"ref_uids"`                 // @我的用户（[1001,1002]）
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName ChatGroupMessage's table name
func (*ChatGroupMessage) TableName() string {
	return TableNameChatGroupMessage
}
