// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: comet.proto

package pb

import (
	protocol "github.com/zhixunjie/im-fun/api/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// users
type SendToUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TcpSessionIds []string               `protobuf:"bytes,1,rep,name=tcpSessionIds,proto3" json:"tcpSessionIds,omitempty"`
	Proto         *protocol.Proto        `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	SubId         int32                  `protobuf:"varint,3,opt,name=subId,proto3" json:"subId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUsersReq) Reset() {
	*x = SendToUsersReq{}
	mi := &file_comet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUsersReq) ProtoMessage() {}

func (x *SendToUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUsersReq.ProtoReflect.Descriptor instead.
func (*SendToUsersReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{0}
}

func (x *SendToUsersReq) GetTcpSessionIds() []string {
	if x != nil {
		return x.TcpSessionIds
	}
	return nil
}

func (x *SendToUsersReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *SendToUsersReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

type SendToUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUsersResp) Reset() {
	*x = SendToUsersResp{}
	mi := &file_comet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUsersResp) ProtoMessage() {}

func (x *SendToUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUsersResp.ProtoReflect.Descriptor instead.
func (*SendToUsersResp) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{1}
}

// all users
type SendToAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         *protocol.Proto        `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	SubId         int32                  `protobuf:"varint,2,opt,name=subId,proto3" json:"subId,omitempty"`
	Speed         int32                  `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToAllReq) Reset() {
	*x = SendToAllReq{}
	mi := &file_comet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToAllReq) ProtoMessage() {}

func (x *SendToAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToAllReq.ProtoReflect.Descriptor instead.
func (*SendToAllReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{2}
}

func (x *SendToAllReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *SendToAllReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *SendToAllReq) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type SendToAllResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToAllResp) Reset() {
	*x = SendToAllResp{}
	mi := &file_comet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToAllResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToAllResp) ProtoMessage() {}

func (x *SendToAllResp) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToAllResp.ProtoReflect.Descriptor instead.
func (*SendToAllResp) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{3}
}

// room users
type SendToRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Proto         *protocol.Proto        `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	SubId         int32                  `protobuf:"varint,3,opt,name=subId,proto3" json:"subId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToRoomReq) Reset() {
	*x = SendToRoomReq{}
	mi := &file_comet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToRoomReq) ProtoMessage() {}

func (x *SendToRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToRoomReq.ProtoReflect.Descriptor instead.
func (*SendToRoomReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{4}
}

func (x *SendToRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendToRoomReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *SendToRoomReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

type SendToRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToRoomResp) Reset() {
	*x = SendToRoomResp{}
	mi := &file_comet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToRoomResp) ProtoMessage() {}

func (x *SendToRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToRoomResp.ProtoReflect.Descriptor instead.
func (*SendToRoomResp) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{5}
}

// room's
type GetAllRoomIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRoomIdReq) Reset() {
	*x = GetAllRoomIdReq{}
	mi := &file_comet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRoomIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomIdReq) ProtoMessage() {}

func (x *GetAllRoomIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomIdReq.ProtoReflect.Descriptor instead.
func (*GetAllRoomIdReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{6}
}

type GetAllRoomIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         map[string]bool        `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRoomIdResp) Reset() {
	*x = GetAllRoomIdResp{}
	mi := &file_comet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRoomIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomIdResp) ProtoMessage() {}

func (x *GetAllRoomIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomIdResp.ProtoReflect.Descriptor instead.
func (*GetAllRoomIdResp) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllRoomIdResp) GetRooms() map[string]bool {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_comet_proto protoreflect.FileDescriptor

const file_comet_proto_rawDesc = "" +
	"\n" +
	"\vcomet.proto\x12\vimfun.comet\x1a\x0eprotocol.proto\"y\n" +
	"\x0eSendToUsersReq\x12$\n" +
	"\rtcpSessionIds\x18\x01 \x03(\tR\rtcpSessionIds\x12+\n" +
	"\x05proto\x18\x02 \x01(\v2\x15.imfun.protocol.ProtoR\x05proto\x12\x14\n" +
	"\x05subId\x18\x03 \x01(\x05R\x05subId\"\x11\n" +
	"\x0fSendToUsersResp\"g\n" +
	"\fSendToAllReq\x12+\n" +
	"\x05proto\x18\x01 \x01(\v2\x15.imfun.protocol.ProtoR\x05proto\x12\x14\n" +
	"\x05subId\x18\x02 \x01(\x05R\x05subId\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x05R\x05speed\"\x0f\n" +
	"\rSendToAllResp\"j\n" +
	"\rSendToRoomReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12+\n" +
	"\x05proto\x18\x02 \x01(\v2\x15.imfun.protocol.ProtoR\x05proto\x12\x14\n" +
	"\x05subId\x18\x03 \x01(\x05R\x05subId\"\x10\n" +
	"\x0eSendToRoomResp\"\x11\n" +
	"\x0fGetAllRoomIdReq\"\x8c\x01\n" +
	"\x10GetAllRoomIdResp\x12>\n" +
	"\x05rooms\x18\x01 \x03(\v2(.imfun.comet.GetAllRoomIdResp.RoomsEntryR\x05rooms\x1a8\n" +
	"\n" +
	"RoomsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\xa9\x02\n" +
	"\x05Comet\x12H\n" +
	"\vSendToUsers\x12\x1b.imfun.comet.SendToUsersReq\x1a\x1c.imfun.comet.SendToUsersResp\x12E\n" +
	"\n" +
	"SendToRoom\x12\x1a.imfun.comet.SendToRoomReq\x1a\x1b.imfun.comet.SendToRoomResp\x12B\n" +
	"\tSendToAll\x12\x19.imfun.comet.SendToAllReq\x1a\x1a.imfun.comet.SendToAllResp\x12K\n" +
	"\fGetAllRoomId\x12\x1c.imfun.comet.GetAllRoomIdReq\x1a\x1d.imfun.comet.GetAllRoomIdRespB'Z%github.com/zhixunjie/im-fun/api/pb;pbb\x06proto3"

var (
	file_comet_proto_rawDescOnce sync.Once
	file_comet_proto_rawDescData []byte
)

func file_comet_proto_rawDescGZIP() []byte {
	file_comet_proto_rawDescOnce.Do(func() {
		file_comet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comet_proto_rawDesc), len(file_comet_proto_rawDesc)))
	})
	return file_comet_proto_rawDescData
}

var file_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_comet_proto_goTypes = []any{
	(*SendToUsersReq)(nil),   // 0: imfun.comet.SendToUsersReq
	(*SendToUsersResp)(nil),  // 1: imfun.comet.SendToUsersResp
	(*SendToAllReq)(nil),     // 2: imfun.comet.SendToAllReq
	(*SendToAllResp)(nil),    // 3: imfun.comet.SendToAllResp
	(*SendToRoomReq)(nil),    // 4: imfun.comet.SendToRoomReq
	(*SendToRoomResp)(nil),   // 5: imfun.comet.SendToRoomResp
	(*GetAllRoomIdReq)(nil),  // 6: imfun.comet.GetAllRoomIdReq
	(*GetAllRoomIdResp)(nil), // 7: imfun.comet.GetAllRoomIdResp
	nil,                      // 8: imfun.comet.GetAllRoomIdResp.RoomsEntry
	(*protocol.Proto)(nil),   // 9: imfun.protocol.Proto
}
var file_comet_proto_depIdxs = []int32{
	9, // 0: imfun.comet.SendToUsersReq.proto:type_name -> imfun.protocol.Proto
	9, // 1: imfun.comet.SendToAllReq.proto:type_name -> imfun.protocol.Proto
	9, // 2: imfun.comet.SendToRoomReq.proto:type_name -> imfun.protocol.Proto
	8, // 3: imfun.comet.GetAllRoomIdResp.rooms:type_name -> imfun.comet.GetAllRoomIdResp.RoomsEntry
	0, // 4: imfun.comet.Comet.SendToUsers:input_type -> imfun.comet.SendToUsersReq
	4, // 5: imfun.comet.Comet.SendToRoom:input_type -> imfun.comet.SendToRoomReq
	2, // 6: imfun.comet.Comet.SendToAll:input_type -> imfun.comet.SendToAllReq
	6, // 7: imfun.comet.Comet.GetAllRoomId:input_type -> imfun.comet.GetAllRoomIdReq
	1, // 8: imfun.comet.Comet.SendToUsers:output_type -> imfun.comet.SendToUsersResp
	5, // 9: imfun.comet.Comet.SendToRoom:output_type -> imfun.comet.SendToRoomResp
	3, // 10: imfun.comet.Comet.SendToAll:output_type -> imfun.comet.SendToAllResp
	7, // 11: imfun.comet.Comet.GetAllRoomId:output_type -> imfun.comet.GetAllRoomIdResp
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_comet_proto_init() }
func file_comet_proto_init() {
	if File_comet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comet_proto_rawDesc), len(file_comet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comet_proto_goTypes,
		DependencyIndexes: file_comet_proto_depIdxs,
		MessageInfos:      file_comet_proto_msgTypes,
	}.Build()
	File_comet_proto = out.File
	file_comet_proto_goTypes = nil
	file_comet_proto_depIdxs = nil
}
