// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: comet.proto

package pb

import (
	protocol "github.com/zhixunjie/im-fun/api/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// users
type SendToUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TcpSessionIds []string        `protobuf:"bytes,1,rep,name=tcpSessionIds,proto3" json:"tcpSessionIds,omitempty"`
	Proto         *protocol.Proto `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	SubId         int32           `protobuf:"varint,3,opt,name=subId,proto3" json:"subId,omitempty"`
}

func (x *SendToUsersReq) Reset() {
	*x = SendToUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUsersReq) ProtoMessage() {}

func (x *SendToUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUsersReq.ProtoReflect.Descriptor instead.
func (*SendToUsersReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{0}
}

func (x *SendToUsersReq) GetTcpSessionIds() []string {
	if x != nil {
		return x.TcpSessionIds
	}
	return nil
}

func (x *SendToUsersReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *SendToUsersReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

type SendToUsersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendToUsersReply) Reset() {
	*x = SendToUsersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUsersReply) ProtoMessage() {}

func (x *SendToUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUsersReply.ProtoReflect.Descriptor instead.
func (*SendToUsersReply) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{1}
}

// all users
type SendToAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proto *protocol.Proto `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	SubId int32           `protobuf:"varint,2,opt,name=subId,proto3" json:"subId,omitempty"`
	Speed int32           `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *SendToAllReq) Reset() {
	*x = SendToAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToAllReq) ProtoMessage() {}

func (x *SendToAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToAllReq.ProtoReflect.Descriptor instead.
func (*SendToAllReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{2}
}

func (x *SendToAllReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *SendToAllReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *SendToAllReq) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type SendToAllReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendToAllReply) Reset() {
	*x = SendToAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToAllReply) ProtoMessage() {}

func (x *SendToAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToAllReply.ProtoReflect.Descriptor instead.
func (*SendToAllReply) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{3}
}

// room users
type SendToRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string          `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Proto  *protocol.Proto `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	SubId  int32           `protobuf:"varint,3,opt,name=subId,proto3" json:"subId,omitempty"`
}

func (x *SendToRoomReq) Reset() {
	*x = SendToRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToRoomReq) ProtoMessage() {}

func (x *SendToRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToRoomReq.ProtoReflect.Descriptor instead.
func (*SendToRoomReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{4}
}

func (x *SendToRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendToRoomReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *SendToRoomReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

type SendToRoomReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendToRoomReply) Reset() {
	*x = SendToRoomReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToRoomReply) ProtoMessage() {}

func (x *SendToRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToRoomReply.ProtoReflect.Descriptor instead.
func (*SendToRoomReply) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{5}
}

// room's
type GetAllRoomIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllRoomIdReq) Reset() {
	*x = GetAllRoomIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRoomIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomIdReq) ProtoMessage() {}

func (x *GetAllRoomIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomIdReq.ProtoReflect.Descriptor instead.
func (*GetAllRoomIdReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{6}
}

type GetAllRoomIdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms map[string]bool `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetAllRoomIdReply) Reset() {
	*x = GetAllRoomIdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRoomIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomIdReply) ProtoMessage() {}

func (x *GetAllRoomIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomIdReply.ProtoReflect.Descriptor instead.
func (*GetAllRoomIdReply) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllRoomIdReply) GetRooms() map[string]bool {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_comet_proto protoreflect.FileDescriptor

var file_comet_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69,
	0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x1a, 0x0e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x0e, 0x53, 0x65,
	0x6e, 0x64, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d,
	0x74, 0x63, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x63, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x73, 0x75, 0x62, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x67, 0x0a, 0x0c, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x6a, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x2b, 0x0a,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69,
	0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x75,
	0x62, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64,
	0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x52, 0x65, 0x71, 0x22, 0x8e, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x05,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x69, 0x6d,
	0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x1a, 0x38, 0x0a,
	0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xad, 0x02, 0x0a, 0x05, 0x43, 0x6f, 0x6d, 0x65,
	0x74, 0x12, 0x49, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x1b, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e,
	0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x46, 0x0a, 0x0a,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1a, 0x2e, 0x69, 0x6d, 0x66,
	0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63,
	0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x41, 0x6c,
	0x6c, 0x12, 0x19, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x69,
	0x6d, 0x66, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x6f, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x69, 0x6d, 0x66, 0x75,
	0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x69, 0x6d, 0x66, 0x75, 0x6e, 0x2e,
	0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x69, 0x78, 0x75, 0x6e, 0x6a, 0x69, 0x65, 0x2f,
	0x69, 0x6d, 0x2d, 0x66, 0x75, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comet_proto_rawDescOnce sync.Once
	file_comet_proto_rawDescData = file_comet_proto_rawDesc
)

func file_comet_proto_rawDescGZIP() []byte {
	file_comet_proto_rawDescOnce.Do(func() {
		file_comet_proto_rawDescData = protoimpl.X.CompressGZIP(file_comet_proto_rawDescData)
	})
	return file_comet_proto_rawDescData
}

var file_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_comet_proto_goTypes = []interface{}{
	(*SendToUsersReq)(nil),    // 0: imfun.comet.SendToUsersReq
	(*SendToUsersReply)(nil),  // 1: imfun.comet.SendToUsersReply
	(*SendToAllReq)(nil),      // 2: imfun.comet.SendToAllReq
	(*SendToAllReply)(nil),    // 3: imfun.comet.SendToAllReply
	(*SendToRoomReq)(nil),     // 4: imfun.comet.SendToRoomReq
	(*SendToRoomReply)(nil),   // 5: imfun.comet.SendToRoomReply
	(*GetAllRoomIdReq)(nil),   // 6: imfun.comet.GetAllRoomIdReq
	(*GetAllRoomIdReply)(nil), // 7: imfun.comet.GetAllRoomIdReply
	nil,                       // 8: imfun.comet.GetAllRoomIdReply.RoomsEntry
	(*protocol.Proto)(nil),    // 9: imfun.protocol.Proto
}
var file_comet_proto_depIdxs = []int32{
	9, // 0: imfun.comet.SendToUsersReq.proto:type_name -> imfun.protocol.Proto
	9, // 1: imfun.comet.SendToAllReq.proto:type_name -> imfun.protocol.Proto
	9, // 2: imfun.comet.SendToRoomReq.proto:type_name -> imfun.protocol.Proto
	8, // 3: imfun.comet.GetAllRoomIdReply.rooms:type_name -> imfun.comet.GetAllRoomIdReply.RoomsEntry
	0, // 4: imfun.comet.Comet.SendToUsers:input_type -> imfun.comet.SendToUsersReq
	4, // 5: imfun.comet.Comet.SendToRoom:input_type -> imfun.comet.SendToRoomReq
	2, // 6: imfun.comet.Comet.SendToAll:input_type -> imfun.comet.SendToAllReq
	6, // 7: imfun.comet.Comet.GetAllRoomId:input_type -> imfun.comet.GetAllRoomIdReq
	1, // 8: imfun.comet.Comet.SendToUsers:output_type -> imfun.comet.SendToUsersReply
	5, // 9: imfun.comet.Comet.SendToRoom:output_type -> imfun.comet.SendToRoomReply
	3, // 10: imfun.comet.Comet.SendToAll:output_type -> imfun.comet.SendToAllReply
	7, // 11: imfun.comet.Comet.GetAllRoomId:output_type -> imfun.comet.GetAllRoomIdReply
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_comet_proto_init() }
func file_comet_proto_init() {
	if File_comet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToUsersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToRoomReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRoomIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRoomIdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comet_proto_goTypes,
		DependencyIndexes: file_comet_proto_depIdxs,
		MessageInfos:      file_comet_proto_msgTypes,
	}.Build()
	File_comet_proto = out.File
	file_comet_proto_rawDesc = nil
	file_comet_proto_goTypes = nil
	file_comet_proto_depIdxs = nil
}
